PREFIX sport: <https://sportschema.org/ontologies/main/>
PREFIX bvo: <https://github.com/andreazammarchi3/BeachVolleyballOntology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Query that returns the average number of attacks per match of the athlete Mario Rossi in the competition World Tour 2024 Cancun

SELECT ?athlete ?competition (AVG(?attacks) AS ?averageAttacks)
WHERE {
    ?athlete rdfs:label "Mario Rossi"@en .

    ?competition rdfs:label "World Tour 2024 Cancun"@en .

    ?match a bvo:Match .
    ?match sport:matchInCompetition ?competition .

    ?performance a bvo:AthletePerfomance .
    ?performance bvo:performanceOf ?athlete .
    ?performance bvo:performanceIn ?match .
    ?performance bvo:attacks ?attacks .
}
GROUP BY ?athlete ?competition
