PREFIX sport: <https://sportschema.org/ontologies/main/> 
PREFIX bv: <https://github.com/andreazammarchi3/BeachVolleyballOntology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?performance ?attacks
WHERE {
    ?performance a bv:AthletePerformance ;
                 bv:performanceIn ?competition ;
                 bv:performanceOf ?player ;
                 bv:attacks ?attacks .
    ?competition rdfs:label "World Tour 2024 Cancun"@en .
    ?player rdfs:label "Mario Rossi"@en .
}
