
PREFIX : <https://github.com/andreazammarchi3/BeachVolleyballOntology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# What is the average number of block errors per match by players of team X in the competition Y?

SELECT (AVG(?blockErrors) AS ?averageBlockErrors)
WHERE {
  ?performance :blockErrors ?blockErrors ;
               :hasPlayer ?player ;
               :partOfMatch ?match .
  ?match :participation :TeamX ;
         :partOfCompetition :CompetitionY .
}
