PREFIX sport: <https://sportschema.org/ontologies/main/>
PREFIX bvo: <https://github.com/andreazammarchi3/BeachVolleyballOntology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Query that returns the average number of block errors per match by players of team Italy in the competition World Tour 2024 Cancun

SELECT ?team ?competition (AVG(?blockErrors) AS ?averageBlockErrors)
WHERE {
    ?team rdfs:label "Team Italy"@en .

    ?athlete sport:memberOf ?team .

    ?competition rdfs:label "World Tour 2024 Cancun"@en .

    ?match a bvo:Match .
    ?match sport:matchInCompetition ?competition .

    ?performance a bvo:AthletePerfomance .
    ?performance bvo:performanceOf ?athlete .
    ?performance bvo:performanceIn ?match .
    ?performance bvo:blockErrors ?blockErrors .
}
GROUP BY ?team ?competition
