PREFIX sport: <https://sportschema.org/ontologies/main/>
PREFIX bvo: <https://github.com/andreazammarchi3/BeachVolleyballOntology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# Query to count the number of matches Team Italy participated in during the competition World Tour 2024 Cancun

SELECT ?team ?competition (COUNT(DISTINCT ?match) AS ?numberOfMatches)
WHERE {
    ?team rdfs:label "Team Italy"@en .

    ?athlete sport:memberOf ?team .

    ?competition rdfs:label "World Tour 2024 Cancun"@en .

    ?match sport:matchInCompetition ?competition .

    ?performance a bvo:AthletePerfomance .
    ?performance bvo:performanceOf ?athlete .
    ?performance bvo:performanceIn ?match .
}
GROUP BY ?team ?competition
