PREFIX sport: <https://sportschema.org/ontologies/main/>
PREFIX bvo: <https://github.com/andreazammarchi3/BeachVolleyballOntology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# Query to calculate the percentage of winning attacks out of all attacks made by Mario Rossi in the competition World Tour 2024 Cancun

SELECT ?athlete ?competition ((SUM(?winningAttacks) / SUM(?totalAttacks)) * 100 AS ?percentWinningAttacks)
WHERE {
    ?athlete rdfs:label "Mario Rossi"@en .

    ?competition rdfs:label "World Tour 2024 Cancun"@en .

    ?match sport:matchInCompetition ?competition .

    ?performance a bvo:AthletePerfomance .
    ?performance bvo:performanceOf ?athlete .
    ?performance bvo:performanceIn ?match .
    ?performance bvo:attacks ?totalAttacks .
    ?performance bvo:winningAttacks ?winningAttacks .
}
GROUP BY ?athlete ?competition
